### ISSUE TITLE
Double Anchor Tag Bug

### ISSUE THREAD

**Issue by shicholas** [NeonLaw/codebase#642]
<img width="447" alt="Screen Shot 2020-08-08 at 6 57 55 PM" src="https://user-images.githubusercontent.com/889427/89723293-2021ae00-d9a9-11ea-921a-4e77290fbfd5.png">

This happens on pages rendered by MDX. Can you please confirm @nisarhassan12 ?

**Comment by nisarhassan12** [comment]
Yeah. I'm able to reproduce this as well on `/bar-prep`.

I also noticed something similar on the about us page for the `<DesktopHalfMobileFullCard>` component some time ago and I put that on the weekly meeting document which I, later on, forgot to discuss or open an issue for. Sorry about that.

This issue also seems to be happening for links that are not children of another link i.e see the below screenshot:

![image](https://user-images.githubusercontent.com/46004116/89729130-25840480-da4c-11ea-8adb-3788e4c07a9e.png)

The issue seems to be happening quite randomly i.e the link on the Linkedin Icon before which has the exact same markdown structure shows the value of the `href` in the inspector tab

![image](https://user-images.githubusercontent.com/46004116/89729277-6f211f00-da4d-11ea-927b-0f8ee837035a.png)

hovering over it shows in the bottom of the browser that it points to the `about-us` page and not the actual `href` value shown in the screenshot. Same is true for the `Avvo` link. 

![image](https://user-images.githubusercontent.com/46004116/89729311-c7f0b780-da4d-11ea-87c2-83e0d69a2e68.png)

and the weirdest of all is that the first link on the mail icon is working as expected.

I suspect maybe something is broken here not too sure though have not looked too deeply into it:

https://github.com/NeonLaw/codebase/blob/dc5e4a6d69c0bb7fbaea8f5d7ef96bc7fc3c8f2d/packages/shared-ui/src/utils/mdxComponents.tsx#L87

**Comment by shicholas** [comment]
I think this is fixed. Closing
